In [62]:
import numpy as np
import pandas as pd
import warnings
from sklearn import preprocessing
warnings.filterwarnings("ignore")
from sklearn.model_selection import train_test_split

In [66]:
def step_gradient(X,y,learning_rate,no_of_iteration,m):
    
    M = X.shape[0] #row
    N = X.shape[1] #col
    
    m_slope = np.zeros(N)
    for i in range(M):
        x = X[i]
        y_pred = (m*x).sum()
        for j in range(N):
            m_slope[j]+= (-2/M)*(y[i]-y_pred)*x[j]
    m = m-learning_rate*m_slope
    #print(m)
    return m
    
def cost(X, Y, m):
    return ((Y - np.sum(m*X, axis = 1))**2).mean()
    

def gradient_descent(x_train,y_train,learning_rate,no_of_iteration):
    m  = np.zeros(x_train.shape[1])
    for i in range(no_of_iteration):
        m = step_gradient(x_train,y_train,learning_rate,no_of_iteration,m)
        print(i+1, " Cost: ", cost(x_train,y_train, m))  
    return m
    

def predict(X, m):
    return np.sum(m*X, axis = 1)


In [67]:
def run():
    data            = np.genfromtxt("./0000000000002419_training_ccpp_x_y_train.csv",delimiter=",")
    testing         = np.genfromtxt("./0000000000002419_test_ccpp_x_test.csv",delimiter=",")
    no_of_iteration = 10
    learning_rate   = 0.0001 
    x_train,y_train = data[:,:-1],data[:,-1]
    #print(x_train)
    print(testing)
    #np.savetxt("x_train.csv",x_train)
    #print(yesting.shape)
    x_train = np.insert(x_train, x_train.shape[1], 1, axis = 1)  # this is for c , "1" column 
    #print("X_train--")
    #print(x_train)
    x_test  = np.insert(testing, testing.shape[1], 1, axis = 1)
    print("X_test")
    print(x_test)
    
    m = gradient_descent(x_train,y_train,learning_rate,no_of_iteration)
    #print(x_test.shape,m.shape)
    y_pred = predict(x_test,m)
    y_pred = y_pred.reshape(x_test.shape[0],1)
    print(y_pred)
    np.savetxt("output.csv",y_pred,fmt="%.5f")
    
run()

[[  11.95   42.03 1017.58   90.89]
 [  12.07   38.25 1012.67   81.66]
 [  26.91   74.99 1005.64   78.98]
 ...
 [  24.32   66.25 1009.09   91.89]
 [  23.49   42.8  1013.96   65.31]
 [  21.76   60.27 1018.96   85.06]]
X_test
[[1.19500e+01 4.20300e+01 1.01758e+03 9.08900e+01 1.00000e+00]
 [1.20700e+01 3.82500e+01 1.01267e+03 8.16600e+01 1.00000e+00]
 [2.69100e+01 7.49900e+01 1.00564e+03 7.89800e+01 1.00000e+00]
 ...
 [2.43200e+01 6.62500e+01 1.00909e+03 9.18900e+01 1.00000e+00]
 [2.34900e+01 4.28000e+01 1.01396e+03 6.53100e+01 1.00000e+00]
 [2.17600e+01 6.02700e+01 1.01896e+03 8.50600e+01 1.00000e+00]]
1  Cost:  8772344518.631067
2  Cost:  372580082470001.2
3  Cost:  1.5824266969013443e+19
4  Cost:  6.720902079539372e+23
5  Cost:  2.8545097761057653e+28
6  Cost:  1.2123708938848012e+33
7  Cost:  5.149196533298462e+37
8  Cost:  2.186973068412523e+42
9  Cost:  9.288538844909722e+46
10  Cost:  3.945039612948826e+51
[[-6.31027106e+25]
 [-6.27475794e+25]
 [-6.24421441e+25]
 ...
 [-6.26797493e+

## Using inbuilt classifier

In [101]:
training_data  = np.genfromtxt("./0000000000002419_training_ccpp_x_y_train.csv",delimiter=",")
testing        = np.genfromtxt("./0000000000002419_test_ccpp_x_test.csv",delimiter=",")

In [102]:
training_data.shape,testing.shape

((7176, 5), (2392, 4))

In [103]:
X_train = training_data[:,:-1]
X_train.shape

(7176, 4)

In [104]:
y_train = training_data[:,-1]
y_train.shape

(7176,)

In [105]:
x_test = testing

In [118]:
from sklearn import preprocessing
std_scalar = preprocessing.StandardScaler()
X_train = std_scalar.fit_transform(X_train,y_train)
x_test = std_scalar.transform(x_test)

In [119]:
from sklearn.linear_model import LinearRegression

In [120]:
lr = LinearRegression()

In [121]:
lr.fit(X_train,y_train)

LinearRegression()

In [122]:
y_pred = lr.predict(x_test)

In [123]:
lr.score(X_train,y_train)

0.9287632000440599

In [124]:
np.savetxt("output.csv",y_pred,fmt="%.5f")